### ISSUE TITLE
Error on server start

### ISSUE THREAD

**Issue by Xenophilicy** [Cosmoverse/NoVPN#3]
I get this exception when starting the server with my API key using version 0.0.1 from Poggit:

```log
[11:48:01] [Server thread/CRITICAL]: cosmicpe\novpn\libs\cosmoverse\antivpn\thread\AntiVPNException: "Failed to connect with AntiVPN" (EXCEPTION) in "plugins/NoVPN.phar/src/cosmicpe/novpn/libs/cosmoverse/antivpn/thread/AntiVPNThread" at line 114
```

I am using all the default config settings (except my key of course).

This was generated on a test server running the latest API with no plugins other than DevTools.

**Comment by Muqsit** [comment]
Does this happen all the time (as in the plugin never works for you) or does it happen frequently (if so, how rarely)?

**Comment by Muqsit** [comment]
Addressed in build 14 on poggit https://poggit.pmmp.io/ci/Cosmoverse/NoVPN/NoVPN/dev:14

**Comment by Xenophilicy** [comment]
@Muqsit Am I missing something? The latest commit you pushed just created another problem:

Here's the first one that caused the plugin to crash:
```log
[20:06:27] [Server thread/CRITICAL]: Error: "Class 'cosmoverse\antivpn\AntiVPN' not found" (EXCEPTION) in "plugins/NoVPN-master/src/cosmicpe/novpn/Main" at line 18
```
This is the second one that was thrown after the plugin was force-disabled:
```log
[20:06:27] [Server thread/CRITICAL]: Error: "Call to a member function close() on null" (EXCEPTION) in "plugins/NoVPN-master/src/cosmicpe/novpn/Main" at line 41
```

**Comment by Xenophilicy** [comment]
Here are the stack traces for each error respectively:

```log
[20:06:27] [Server thread/DEBUG]: #0 src/pocketmine/plugin/PluginBase(115): cosmicpe\novpn\Main->onEnable()
[20:06:27] [Server thread/DEBUG]: #1 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[20:06:27] [Server thread/DEBUG]: #2 src/pocketmine/Server(1782): pocketmine\plugin\PluginManager->enablePlugin(object cosmicpe\novpn\Main)
[20:06:27] [Server thread/DEBUG]: #3 src/pocketmine/Server(1768): pocketmine\Server->enablePlugin(object cosmicpe\novpn\Main)
[20:06:27] [Server thread/DEBUG]: #4 src/pocketmine/Server(1581): pocketmine\Server->enablePlugins(integer 1)
[20:06:27] [Server thread/DEBUG]: #5 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[30] C:\Users\xenop\Documents\Test\, string[38] C:\Users\xenop\Documents\Test\plugins\)
[20:06:27] [Server thread/DEBUG]: #6 src/pocketmine/PocketMine(297): pocketmine\server()
[20:06:27] [Server thread/DEBUG]: #7 (11): require(string[85] phar://C:/Users/xenop/Documents/Test/PocketMine-MP.phar/src/pocketmine/PocketMin)
```

```log
[20:06:27] [Server thread/DEBUG]: #0 src/pocketmine/plugin/PluginBase(117): cosmicpe\novpn\Main->onDisable()
[20:06:27] [Server thread/DEBUG]: #1 src/pocketmine/plugin/PluginManager(628): pocketmine\plugin\PluginBase->setEnabled(boolean )
[20:06:27] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginManager(548): pocketmine\plugin\PluginManager->disablePlugin(object cosmicpe\novpn\Main)
[20:06:27] [Server thread/DEBUG]: #3 src/pocketmine/Server(1782): pocketmine\plugin\PluginManager->enablePlugin(object cosmicpe\novpn\Main)
[20:06:27] [Server thread/DEBUG]: #4 src/pocketmine/Server(1768): pocketmine\Server->enablePlugin(object cosmicpe\novpn\Main)
[20:06:27] [Server thread/DEBUG]: #5 src/pocketmine/Server(1581): pocketmine\Server->enablePlugins(integer 1)
[20:06:27] [Server thread/DEBUG]: #6 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[30] C:\Users\xenop\Documents\Test\, string[38] C:\Users\xenop\Documents\Test\plugins\)
[20:06:27] [Server thread/DEBUG]: #7 src/pocketmine/PocketMine(297): pocketmine\server()
[20:06:27] [Server thread/DEBUG]: #8 (11): require(string[85] phar://C:/Users/xenop/Documents/Test/PocketMine-MP.phar/src/pocketmine/PocketMin)
```

**Comment by Xenophilicy** [comment]
It simply seems that you changed the paths but never the namespaces for the files. I can open a PR with fixed if you'd like.

**Comment by Xenophilicy** [comment]
Upon further investigation, I installed the virion you use from source, and still encounter the error as follows:

```log
[20:30:51] [Server thread/CRITICAL]: cosmicpe\antivpn\thread\AntiVPNException: "Failed to connect with AntiVPN" (EXCEPTION) in "plugins/NoVPN/src/cosmicpe/antivpn/thread/AntiVPNThread" at line 127
```

**Comment by Heisenburger69** [comment]
Can confirm, occurs all the time for me

**Comment by Heisenburger69** [comment]
Just tested on a VPS, the plugin works fine, issue only occurs on a local server

**Comment by Xenophilicy** [comment]
@Heisenburger69 Hmm... Any reason as to why this would only happen on local servers?

**Comment by Heisenburger69** [comment]
Upon further testing, it's not just local servers, issue occurs on premade hosts/other VPS too, maybe an OS thing?

**Comment by Xenophilicy** [comment]
Possibly, the machine I was testing on runs Windows 10 Pro.

**Comment by Heisenburger69** [comment]
`SSL certificate problem: unable to get local issuer certificate`
This is the result of `curl_error($ch)` under run() of AntiVPNThread

**Comment by Muqsit** [comment]
Try the build 16 on poggit, should solve it https://poggit.pmmp.io/ci/Cosmoverse/NoVPN/NoVPN/dev:16

**Comment by Xenophilicy** [comment]
Well, it tried:

```log
Warning: Use of undefined constant JSON_THROW_ON_ERROR - assumed 'JSON_THROW_ON_ERROR' (this will throw an Error in a future version of PHP) in phar://C:/Users/xenop/Documents/Test/plugins/NoVPN_dev-16.phar/src/cosmicpe/novpn/libs/cosmoverse/antivpn/thread/AntiVPNThread.php on line 119

Fatal error: Uncaught TypeError: json_decode() expects parameter 4 to be integer, string given in phar://C:/Users/xenop/Documents/Test/plugins/NoVPN_dev-16.phar/src/cosmicpe/novpn/libs/cosmoverse/antivpn/thread/AntiVPNThread.php:119
Stack trace:
#0 phar://C:/Users/xenop/Documents/Test/plugins/NoVPN_dev-16.phar/src/cosmicpe/novpn/libs/cosmoverse/antivpn/thread/AntiVPNThread.php(119): json_decode('{"success":true...', true, 512, 'JSON_THROW_ON_E...')
#1 [internal function]: cosmicpe\novpn\libs\cosmoverse\antivpn\thread\AntiVPNThread->run()
#2 {main}
```

**Comment by Muqsit** [comment]
@Xenophilicy you are using an unofficial PHP binary, compile one using pmmp/php-build-scripts or get one from pmmp's jenkins.

**Comment by Xenophilicy** [comment]
Wow, didn't even know I had an unofficial binary lol. It does load, however it doesn't really block VPNs. I've tried 3 so far: X-VPN, ExpressVPN, and CyberGhost all located in Chicago, Illinois, USA. Is this an expected result?

**Comment by Muqsit** [comment]
@Xenophilicy Not really, but you can create an issue on https://github.com/Cosmoverse/AntiVPN about it (please provide the IP address though).

**Comment by Xenophilicy** [comment]
Alright, will do, thanks!
